Improved some SSE routines and added examples directory.

diff --git a/lib/make_qla_dirs b/lib/make_qla_dirs
--- a/lib/make_qla_dirs
+++ b/lib/make_qla_dirs
@@ -12,7 +12,8 @@ dirs="qla_int \
 
 incdir='$(top_builddir)/include'
 
-rm -rf $dirs
+# CVS doesn't like us to remove the CVS directories
+#rm -rf $dirs
 
 for dir in $dirs; do
   lib="lib$dir"
@@ -25,10 +26,22 @@ for dir in $dirs; do
     qla_d[fq][23n]) hdrs="$hdr ${idir}_color_generic.h";;
     *)              hdrs="$hdr";;
   esac
-  mkdir $dir
 
   echo $dir
-  cd $dir
+  if [ -d $dir ]; then
+    echo Found $dir
+    if cd $dir; then
+      \ls -1A |grep -v CVS |xargs rm -rf
+    else
+      echo "Can't enter directory $dir"
+      exit 1
+    fi
+  else
+    echo Creating $dir
+    mkdir $dir
+    cd $dir
+  fi
+
   perl ../perl/build_qla.pl ${tag} ${dir}.h .
   \ls -1 | grep 'QLA.*\.c' > src_list
   nl=`wc src_list | sed 's/^[^0-9]*\([0-9]*\)[^0-9].*/\1/'`
